In [24]:
import numpy as np
import jax
import jax.numpy as jnp
import scipy.stats as ss
import tensorly as tl
tl.set_backend('jax')
# import matplotlib.pyplot as plt
# %matplotlib inline
# from IPython.display import display
# import sympy; sympy.init_printing()

# def display_matrix(m):
#     display(sympy.Matrix(m))

In [40]:
sample = np.genfromtxt('references/sample.csv', delimiter=',')

In [46]:
S = jnp.transpose(sample)
print(S[:3,3])

[[1.05       1.04856412 1.01787965]
 [1.05       1.02942462 1.00856132]
 [1.05       1.12692091 1.11423357]]


In [62]:
# check distribution
print(S.shape) # paths, time
# print(S[:,-1][:5])

print(np.mean(S[:,-1]))
print(np.std(S[:,-1]))

# 1.05
# 0.2667

(10000, 100)
1.0518324048639505
0.2652238988718132


In [56]:
N = S.shape[1]          # number of time steps
r = 0.05       # interest rate
K = 1          # strike 
T = 1          # Maturity

dt = T/(N-1)          # time interval
df = jnp.exp(-r * dt)  # discount factor per time interval

In [59]:
H = np.maximum(K - S, 0)           # intrinsic values for put option

V = np.zeros_like(H)               # value matrix
V[:,-1] = H[:,-1]

# Valuation by LS Method
for t in range(N-2, 0, -1):

    good_paths = H[:,t] > 0        # paths where the intrinsic value is positive 
                                   # the regression is performed only on these paths 
    
    rg = jnp.polyfit( S[good_paths, t], V[good_paths, t+1] * df, 2)    # polynomial regression
    C = jnp.polyval( rg, S[good_paths,t] )                             # evaluation of regression  
    
    exercise = np.zeros( len(good_paths), dtype=bool)    # initialize
    exercise[good_paths] = H[good_paths,t] > C           # paths where it is optimal to exercise
    
    V[exercise,t] = H[exercise,t]                        # set V equal to H where it is optimal to exercise 
    V[exercise,t+1:] = 0                                 # set future cash flows, for that path, equal to zero  
    discount_path = (V[:,t] == 0)                        # paths where we didn't exercise 
    V[discount_path,t] = V[discount_path,t+1] * df       # set V[t] in continuation region
    
V0 = jnp.mean(V[:,1]) * df  # discounted expectation of V[t=1]
print("Example price= ", V0)

Example price=  0.07364798698126832


In [60]:
print(H.round(2))

[[0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.18 0.15 0.12]
 [0.   0.   0.   ... 0.15 0.16 0.2 ]
 ...
 [0.   0.   0.   ... 0.23 0.26 0.27]
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]]


In [61]:
# 0.0797